### ISSUE TITLE
Custom tabs does not respect default browser

### ISSUE THREAD

**Issue by hjiangsu** [droibit/flutter_custom_tabs#143]
**Issue**
Custom tabs prioritizes Chrome over the default browser's custom tabs. When setting a default browser with support for custom tabs (e.g., Firefox), triggering custom tabs will attempt to open the custom tab in Chrome. Only when Chrome is disabled, custom tabs will open using the default browser's custom tab.

To reproduce this issue:
1. Install a browser that is compatible with custom tabs (Firefox)
2. Set the default browser to the new browser
3. Trigger custom tab to open

**Expected result**
Custom tabs should open using the system's default browser if the default browser supports custom tabs.

**Notes**
This seems to happen both on the latest version `1.2.1` and the latest beta `2.0.0-beta`

**Comment by droibit** [comment]
Hi @hjiangsu,  

Thank you for reporting this issue.

> Custom tabs prioritizes Chrome over the default browser's custom tabs.

This is intended behavior and not a bug. It was fixed in `flutter_custom_tabs` v1.1.0.

It is possible to add an option to `CustomTabsOptions` to prioritize the default browser.   
Is this something you would like?

**Comment by hjiangsu** [comment]
Thanks for clarifying the issue.

> It is possible to add an option to CustomTabsOptions to prioritize the default browser.

Having the option to prioritize the default browser would be great!

**Comment by droibit** [comment]
Got it!

I will add an option to `CustomTabsOptions` to change the priority of the browser to launch.   
Please wait for the next beta release!

**Comment by droibit** [comment]
Hi, 

I've just published the new version `flutter_custom_tabs` v2.0.0-beta.1 to pub.dev.
- https://pub.dev/packages/flutter_custom_tabs/versions/2.0.0-beta.1

This release includes a new option, `prefersDefaultBrowser`, which allows you to prioritize opening a URL in the default browser.  
To use this option, simply update the plugin and add the following code to your project:
```dart
await launchUrl(
  ...,
  customTabsOptions: CustomTabsOptions(
    browser: const CustomTabsBrowserConfiguration(
      prefersDefaultBrowser: true,
    ),
  ),
);
```

**Comment by hjiangsu** [comment]
Thank you for the update! I'll test it out when I have the chance

**Comment by micahmo** [comment]
@droibit Thank you so much for the super fast response on this issue! It'll really help us out.

Purely out of curiosity (no judgement), was there any reasoning for the intentional change to prefer Chrome?

Thanks again!

**Comment by droibit** [comment]
@micahmo  
Thanks for your feedback!

I originally made the decision to prioritize Chrome because at the time of development, 
Custom Tabs support was relatively weak in other browsers. Even today, Chrome is the only browser that supports all Custom Tabs options (reference: [Chrome Custom Tabs Browser Support](https://developer.chrome.com/docs/android/custom-tabs/browser-support/)).

Due to this limitation, the decision was made in`flutter_custom_tabs` to prioritize Chrome.  
However, considering the current progress in supporting Custom Tabs for browsers other than Chrome, I believe it would be a good idea to provide an option to prioritize the default browser on the device :)

**Comment by hjiangsu** [comment]
Version `v2.0.0-beta.1` seems to be working as expected. Thanks again!
